/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampgroundsIndexRouteImport } from './routes/campgrounds/index'
import { Route as CampgroundsNewRouteImport } from './routes/campgrounds/new'
import { Route as CampgroundsIdRouteImport } from './routes/campgrounds/$id'
import { Route as CampgroundsIdIndexRouteImport } from './routes/campgrounds/$id.index'
import { Route as CampgroundsIdEditRouteImport } from './routes/campgrounds/$id.edit'
import { Route as CampgroundsIdCommentsNewRouteImport } from './routes/campgrounds/$id.comments.new'
import { Route as CampgroundsIdCommentsCommentIdEditRouteImport } from './routes/campgrounds/$id.comments.$commentId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampgroundsIndexRoute = CampgroundsIndexRouteImport.update({
  id: '/campgrounds/',
  path: '/campgrounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampgroundsNewRoute = CampgroundsNewRouteImport.update({
  id: '/campgrounds/new',
  path: '/campgrounds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampgroundsIdRoute = CampgroundsIdRouteImport.update({
  id: '/campgrounds/$id',
  path: '/campgrounds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampgroundsIdIndexRoute = CampgroundsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampgroundsIdRoute,
} as any)
const CampgroundsIdEditRoute = CampgroundsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CampgroundsIdRoute,
} as any)
const CampgroundsIdCommentsNewRoute =
  CampgroundsIdCommentsNewRouteImport.update({
    id: '/comments/new',
    path: '/comments/new',
    getParentRoute: () => CampgroundsIdRoute,
  } as any)
const CampgroundsIdCommentsCommentIdEditRoute =
  CampgroundsIdCommentsCommentIdEditRouteImport.update({
    id: '/comments/$commentId/edit',
    path: '/comments/$commentId/edit',
    getParentRoute: () => CampgroundsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/campgrounds/$id': typeof CampgroundsIdRouteWithChildren
  '/campgrounds/new': typeof CampgroundsNewRoute
  '/campgrounds/': typeof CampgroundsIndexRoute
  '/campgrounds/$id/edit': typeof CampgroundsIdEditRoute
  '/campgrounds/$id/': typeof CampgroundsIdIndexRoute
  '/campgrounds/$id/comments/new': typeof CampgroundsIdCommentsNewRoute
  '/campgrounds/$id/comments/$commentId/edit': typeof CampgroundsIdCommentsCommentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/campgrounds/new': typeof CampgroundsNewRoute
  '/campgrounds': typeof CampgroundsIndexRoute
  '/campgrounds/$id/edit': typeof CampgroundsIdEditRoute
  '/campgrounds/$id': typeof CampgroundsIdIndexRoute
  '/campgrounds/$id/comments/new': typeof CampgroundsIdCommentsNewRoute
  '/campgrounds/$id/comments/$commentId/edit': typeof CampgroundsIdCommentsCommentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/campgrounds/$id': typeof CampgroundsIdRouteWithChildren
  '/campgrounds/new': typeof CampgroundsNewRoute
  '/campgrounds/': typeof CampgroundsIndexRoute
  '/campgrounds/$id/edit': typeof CampgroundsIdEditRoute
  '/campgrounds/$id/': typeof CampgroundsIdIndexRoute
  '/campgrounds/$id/comments/new': typeof CampgroundsIdCommentsNewRoute
  '/campgrounds/$id/comments/$commentId/edit': typeof CampgroundsIdCommentsCommentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/campgrounds/$id'
    | '/campgrounds/new'
    | '/campgrounds/'
    | '/campgrounds/$id/edit'
    | '/campgrounds/$id/'
    | '/campgrounds/$id/comments/new'
    | '/campgrounds/$id/comments/$commentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/campgrounds/new'
    | '/campgrounds'
    | '/campgrounds/$id/edit'
    | '/campgrounds/$id'
    | '/campgrounds/$id/comments/new'
    | '/campgrounds/$id/comments/$commentId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/campgrounds/$id'
    | '/campgrounds/new'
    | '/campgrounds/'
    | '/campgrounds/$id/edit'
    | '/campgrounds/$id/'
    | '/campgrounds/$id/comments/new'
    | '/campgrounds/$id/comments/$commentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CampgroundsIdRoute: typeof CampgroundsIdRouteWithChildren
  CampgroundsNewRoute: typeof CampgroundsNewRoute
  CampgroundsIndexRoute: typeof CampgroundsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campgrounds/': {
      id: '/campgrounds/'
      path: '/campgrounds'
      fullPath: '/campgrounds/'
      preLoaderRoute: typeof CampgroundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campgrounds/new': {
      id: '/campgrounds/new'
      path: '/campgrounds/new'
      fullPath: '/campgrounds/new'
      preLoaderRoute: typeof CampgroundsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campgrounds/$id': {
      id: '/campgrounds/$id'
      path: '/campgrounds/$id'
      fullPath: '/campgrounds/$id'
      preLoaderRoute: typeof CampgroundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campgrounds/$id/': {
      id: '/campgrounds/$id/'
      path: '/'
      fullPath: '/campgrounds/$id/'
      preLoaderRoute: typeof CampgroundsIdIndexRouteImport
      parentRoute: typeof CampgroundsIdRoute
    }
    '/campgrounds/$id/edit': {
      id: '/campgrounds/$id/edit'
      path: '/edit'
      fullPath: '/campgrounds/$id/edit'
      preLoaderRoute: typeof CampgroundsIdEditRouteImport
      parentRoute: typeof CampgroundsIdRoute
    }
    '/campgrounds/$id/comments/new': {
      id: '/campgrounds/$id/comments/new'
      path: '/comments/new'
      fullPath: '/campgrounds/$id/comments/new'
      preLoaderRoute: typeof CampgroundsIdCommentsNewRouteImport
      parentRoute: typeof CampgroundsIdRoute
    }
    '/campgrounds/$id/comments/$commentId/edit': {
      id: '/campgrounds/$id/comments/$commentId/edit'
      path: '/comments/$commentId/edit'
      fullPath: '/campgrounds/$id/comments/$commentId/edit'
      preLoaderRoute: typeof CampgroundsIdCommentsCommentIdEditRouteImport
      parentRoute: typeof CampgroundsIdRoute
    }
  }
}

interface CampgroundsIdRouteChildren {
  CampgroundsIdEditRoute: typeof CampgroundsIdEditRoute
  CampgroundsIdIndexRoute: typeof CampgroundsIdIndexRoute
  CampgroundsIdCommentsNewRoute: typeof CampgroundsIdCommentsNewRoute
  CampgroundsIdCommentsCommentIdEditRoute: typeof CampgroundsIdCommentsCommentIdEditRoute
}

const CampgroundsIdRouteChildren: CampgroundsIdRouteChildren = {
  CampgroundsIdEditRoute: CampgroundsIdEditRoute,
  CampgroundsIdIndexRoute: CampgroundsIdIndexRoute,
  CampgroundsIdCommentsNewRoute: CampgroundsIdCommentsNewRoute,
  CampgroundsIdCommentsCommentIdEditRoute:
    CampgroundsIdCommentsCommentIdEditRoute,
}

const CampgroundsIdRouteWithChildren = CampgroundsIdRoute._addFileChildren(
  CampgroundsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CampgroundsIdRoute: CampgroundsIdRouteWithChildren,
  CampgroundsNewRoute: CampgroundsNewRoute,
  CampgroundsIndexRoute: CampgroundsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
